[package]
name = "sako-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "sako"
path = "src/main.rs"

[dependencies]
sako-diagnostics = { path = "../sako-diagnostics" }
sako-package = { path = "../sako-package" }
sako-process = { path = "../sako-process" }
sako-v8 = { path = "../sako-v8" }
serde_json = "1.0"
